### ISSUE TITLE
Crash when starting with a different project template

### ISSUE THREAD

**Issue by Thane5** [AIGODLIKE/Colorista#4]
Steps to reproduce:

- On the blender splash screen, select "VFX" as the project template.
- Open a new 3d viewport.
- On the N-panel, select the clorista tab
- -> Blender has now crashed.

**Comment by Acennnn** [comment]
me to

**Comment by Yorha4D** [comment]
@Thane5 This issue occurred in Blender 4.3 version
1. In CPU mode, use a certain Composition node
2. Rendering, prompting Composition initialization error
3. Blender crashes
Using GPU or Blender 4.2 will not cause such problems

**Comment by Yorha4D** [comment]
@Thane5 @Acennnn 1.1.2
